"""add_portfolio_value_cash_balance_to_daily_snapshot

Revision ID: 08a6fbe80b17
Revises: 1b362f294441
Create Date: 2026-06-23 21:38:47.340847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a6fbe80b17'
down_revision: Union[str, Sequence[str], None] = '1b362f294441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_snapshots', sa.Column('portfolio_value', sa.Float(), nullable=True))
    op.add_column('daily_snapshots', sa.Column('cash_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_snapshots', 'cash_balance')
    op.drop_column('daily_snapshots', 'portfolio_value')
    # ### end Alembic commands ###
