"""add_trades_won_lost_to_daily_snapshot

Revision ID: 1b362f294441
Revises: 2491e2cf6f40
Create Date: 2026-06-21 15:33:58.528196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b362f294441'
down_revision: Union[str, Sequence[str], None] = '2491e2cf6f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_snapshots', sa.Column('trades_won', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('daily_snapshots', sa.Column('trades_lost', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_snapshots', 'trades_lost')
    op.drop_column('daily_snapshots', 'trades_won')
    # ### end Alembic commands ###
