"""phase2_agent_fields_and_new_tables

Revision ID: 8f0215e54b42
Revises: 
Create Date: 2026-06-18 17:54:23.734292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0215e54b42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_name')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('timeout_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.add_column('agents', sa.Column('room', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('broker', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('context_file_path', sa.String(length=255), nullable=True))
    op.add_column('agents', sa.Column('confidence_score', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('execution_mode', sa.String(length=20), nullable=True))
    op.add_column('agents', sa.Column('check_frequency', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('paper_trading_balance', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('consecutive_losses', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('grid_col', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('grid_row', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('use_local_llm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'use_local_llm')
    op.drop_column('agents', 'grid_row')
    op.drop_column('agents', 'grid_col')
    op.drop_column('agents', 'consecutive_losses')
    op.drop_column('agents', 'paper_trading_balance')
    op.drop_column('agents', 'check_frequency')
    op.drop_column('agents', 'execution_mode')
    op.drop_column('agents', 'confidence_score')
    op.drop_column('agents', 'context_file_path')
    op.drop_column('agents', 'broker')
    op.drop_column('agents', 'room')
    op.drop_table('pending_approvals')
    op.drop_table('logs')
    op.drop_table('broker_configs')
    # ### end Alembic commands ###
